import { Task } from '@/types'

export const TASKS: Task[] = [
  {
    id: '1',
    title: 'Brand Identity Refresh',
    category: 'design',
    org: 'RefugeeAid Kenya',
    orgInitial: 'R',
    orgColor: '#7EE000',
    description: 'Redesign logo and visual identity for a non-profit operating across 3 East African countries. SVG files + brand guide PDF.',
    reward: 35,
    deadline: '48hr',
    submissions: 3,
    postedAt: '2h ago',
  },
  {
    id: '2',
    title: 'Smart Contract Audit',
    category: 'code',
    org: 'OpenFin Protocol',
    orgInitial: 'O',
    orgColor: '#4A90D9',
    description: 'Review a 200-line Solidity escrow contract for reentrancy vulnerabilities and gas optimizations. Written report required.',
    reward: 50,
    deadline: '72hr',
    submissions: 1,
    postedAt: '5h ago',
  },
  {
    id: '3',
    title: 'Amharic → English Docs',
    category: 'translation',
    org: 'IOM Ethiopia',
    orgInitial: 'I',
    orgColor: '#F5A623',
    description: 'Translate 4 pages of community health guidelines. Medical literacy required. Accurate terminology is essential.',
    reward: 22,
    deadline: '24hr',
    submissions: 5,
    postedAt: '1h ago',
  },
  {
    id: '4',
    title: 'React Dashboard UI',
    category: 'code',
    org: 'GirlCode Lagos',
    orgInitial: 'G',
    orgColor: '#9333ea',
    description: 'Build a responsive analytics dashboard component in React with Recharts. Mobile-first, clean and documented code.',
    reward: 45,
    deadline: '72hr',
    submissions: 2,
    postedAt: '3h ago',
  },
  {
    id: '5',
    title: 'Infographic Series (×4)',
    category: 'design',
    org: 'UNHCR Digital',
    orgInitial: 'U',
    orgColor: '#5AB800',
    description: '4-part infographic series on refugee rights for social media. Figma source files + exported PNGs. Brand kit provided.',
    reward: 40,
    deadline: '48hr',
    submissions: 7,
    postedAt: '6h ago',
  },
  {
    id: '6',
    title: 'Swahili Field Manual',
    category: 'translation',
    org: 'Médecins Sans F.',
    orgInitial: 'M',
    orgColor: '#e11d48',
    description: 'Translate a 6-page medical field manual from English to Swahili. Native fluency required. PDF deliverable.',
    reward: 28,
    deadline: '36hr',
    submissions: 4,
    postedAt: '4h ago',
  },
]

export const HOW_IT_WORKS = [
  {
    num: '01',
    icon: '👛',
    title: 'Connect a Wallet',
    desc: 'Any Avalanche-compatible wallet. No ID upload. No bank account. Your wallet is your identity.',
  },
  {
    num: '02',
    icon: '🎯',
    title: 'Claim a Task',
    desc: 'Browse the open task pool. Claim what matches your skills. Deadline and reward are fixed upfront.',
  },
  {
    num: '03',
    icon: '⚡',
    title: 'Get Paid Instantly',
    desc: 'Approval triggers a smart contract. USDC lands in your wallet in under 2 seconds. No middlemen.',
  },
  {
    num: '04',
    icon: '🔗',
    title: 'Build Your Proof',
    desc: "Every task writes to your permanent on-chain record. Your POC Score grows. Borders can't touch it.",
  },
]

export const MARQUEE_ITEMS = [
  'NO ID REQUIRED',
  'INSTANT USDC PAYMENT',
  'ON-CHAIN REPUTATION',
  'AVALANCHE C-CHAIN',
  '117M DISPLACED WORKERS',
  'YOUR PROOF. YOUR CHAIN.',
]

export const CATEGORY_STYLES: Record<string, { bg: string; text: string; label: string }> = {
  design:      { bg: 'bg-lime-light',  text: 'text-lime-dark',  label: 'Design' },
  code:        { bg: 'bg-blue-50',     text: 'text-blue-600',   label: 'Code' },
  translation: { bg: 'bg-orange-50',   text: 'text-orange-600', label: 'Translation' },
  data:        { bg: 'bg-purple-50',   text: 'text-purple-600', label: 'Data' },
}